---
title: "Univariante Y Bivariante"
format: html
editor: visual
---

```{r}
library(ggplot2)
library(psych)
library(limma)
library(car)
library(mixOmics)
library(vegan)
library(ggpubr)
library(MOFA2)
library(dplyr)
library(ALDEx2)
```

```{r}
mean_aldex <- function(X) {
  mc.all <- getMonteCarloInstances(X)
  mc.instances <- numMCInstances(X)
  row_mean <- function(y)
    apply(y, 1, mean)
  X <- data.frame(bind_rows(lapply(mc.all, row_mean)))
  rownames(X) <- names(mc.all)
  return(as.data.frame(t(X)))
}

```

## Metaboloma

### Analisis univariante

```{r}
funcion_pca <- function(X, scle, trans) {
  if (!trans) {
    pca <- prcomp(X, scale. = scle)
    
    varianzas <- round(100 * pca$sdev ^ 2 / sum(pca$sdev ^ 2), 2)
    pca.plot <- data.frame(
      PC1 = pca$x[, 1],
      PC2 = pca$x[, 2],
      obesidad = obesidad,
      grupo = grupo,
      sexo = sexo
    )
  } else{
    X <- t(scale(X))
    pca <- prcomp((X), scale. = scle)
    
    varianzas <- round(100 * pca$sdev ^ 2 / sum(pca$sdev ^ 2), 2)
    pca.plot <- data.frame(
      PC1 = pca$rotation[, 1],
      PC2 = pca$rotation[, 2],
      obesidad = obesidad,
      grupo = grupo,
      sexo = sexo
    )
  }
  
  p1 <-
    ggplot(pca.plot, aes(PC1, PC2, color = grupo)) + geom_point() + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2]))
  p2 <-
    ggplot(pca.plot, aes(PC1, PC2, color = grupo)) + geom_point() + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + facet_grid(~ obesidad)
  p3 <-
    ggplot(pca.plot, aes(PC1, PC2, color = sexo)) + geom_point() + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + facet_grid(~ obesidad)
  p4 <- ggarrange(p1, p2, p3)
  p1 <-
    ggplot(pca.plot, aes(PC1, PC2, color = obesidad)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point()
  p2 <-
    ggplot(pca.plot, aes(PC1, PC2, color = obesidad)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point() + facet_grid(~ grupo)
  p3 <-
    ggplot(pca.plot, aes(PC1, PC2, color = obesidad)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point() + facet_grid(~ sexo)
  
  
  p5 <- ggarrange(p1, p2, p3)
  p1 <-
    ggplot(pca.plot, aes(PC1, PC2, color = sexo)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point()
  p2 <-
    ggplot(pca.plot, aes(PC1, PC2, color = sexo)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point() + facet_grid(~ grupo)
  p3 <-
    ggplot(pca.plot, aes(PC1, PC2, color = sexo)) + xlab(paste("PC1", varianzas[1])) +
    ylab(paste("PC2", varianzas[2])) + geom_point() + facet_grid(~ sexo)
  
  
  p6 <- ggarrange(p1, p2, p3)
  
  return(list(p4, p5, p6))
}

add_classificacion_metaboloma <- function(X) {
  aromatic <- rownames(X)[c(2, 3, 4, 1, 6, 35, 36, 34)]
  other <-
    rownames(X)[c(21, 9, 16, 26, 22, 18, 13, 29, 30, 27)]
  aa <- rownames(X)[c(33, 15, 20, 19, 23)]
  carbo <-
    rownames(X)[!rownames(X) %in% c(aromatic, other, aa)]
  
  X$grupo_meta <-
    ifelse(rownames(X) %in% aromatic, "AROMATIC", NA)
  X$grupo_meta <-
    ifelse(rownames(X) %in% other,
           "OTHER",
           X$grupo_meta)
  X$grupo_meta <-
    ifelse(rownames(X) %in% aa,
           "AA",
           X$grupo_meta)
  X$grupo_meta <-
    ifelse(rownames(X) %in% carbo,
           "CARBO",
           X$grupo_meta)
  
  return(X)
}

transform.in.t <- function(x)
  scale(t(x))
```

```{r}
dat <- readRDS("../../datos/preprocesado_08_09_23/novoom.rds")
```

```{r}
x <- dat$comunes$metaboloma[-c(38:40),]
succinato <- colMeans(dat$comunes$metaboloma)
x <- rbind(x,succinato)
rownames(x)[38] <- "Succ"
rownames(x)<- gsub("_mean",replacement = "",x=rownames(x))
x.tmp <- x[-38]
x.tmp <- add_classificacion_metaboloma(x.tmp[-38,])
rownames(x)[-38] <- paste(x.tmp$grupo_meta,rownames(x.tmp),sep="_")
tot <- as.data.frame(transform.in.t(x))
tot <- tot[,order(colnames(tot)),]

grupo <- dat$comunes$grupo
obesidad <- dat$comunes$obesidad

tot$grupo <- grupo
tot$obesidad <- obesidad
tot.melt <- reshape2::melt(tot)

ggplot(tot.melt, aes(value, color = obesidad)) + geom_density()

tot <- as.data.frame(scale(tot[,-c(39,40)]))
mardia(tot)

mdl2 <- model.matrix( ~ 0 + obesidad * grupo)

colnames(mdl2) <-
  c("NO", "Obesidad", "PCOS", "Male", "PCOSObese", "MaleObese")
contraste <- c(
  pcosfemale = "PCOS-(Obesidad+NO)",
  malefemale = "Male-(Obesidad+NO)",
  pcosmale = "PCOS-Male",
  obesidad = "Obesidad-NO",
  pcosfamaleno = "(PCOS-Obesidad)-NO",
  malefemaleno = "(Male-Obesidad)-NO",
  pcosmaleobeno = "(PCOS-Obesidad)-(Male-Obesidad)",
  pcosfemaleob = "PCOSObese-Obesidad",
  malefemaleob = "MaleObese-Obesidad",
  pcosmaleob = "MaleObese-PCOSObese",
  pcosobese = "PCOSObese",
  MaleObese = "MaleObese",
  FemaleObese = "Obesidad"
)


contrastes <-
  makeContrasts(contrasts = contraste, levels = colnames(mdl2))
fit <- lmFit(t(tot), design = mdl2)
fit2 <- contrasts.fit(fit, contrastes)
fit2 <- eBayes(fit2)

modelo2 <- coef(fit2, Inf)
modelo2 <- add_classificacion_metaboloma(as.data.frame(modelo2))
colnames(modelo2)[ncol(modelo2)] <- "GRUPO"

colnames(modelo2) <- names(contraste)
colnames(modelo2)[ncol(modelo2)] <- "GRUPO"
modelo2$metabolito <- rownames(modelo2)
colnames(modelo2) <- c("PCOS_vs_Female",
                       "Male_vs_Female",
                       "PCOS_vs_Male",
                       "NO_vs_O",
                       "NO_PCOS_Female",
                       "NO_Male_Female",
                       "NO_PCOS_Male",
                       "O_PCOS_Female",
                       "O_Male_Female",
                       "O_PCOS_Male",
                       "PCOS_obese",
                       "Male_Obese",
                       "Female_Obese",
                       "GRUPO",
                       "metabolito")

p.values <- sapply(1:13, function(x) topTable(fit2,coef = x,number=Inf)$adj.P.Val)
```

```{r}
funcion_cor <- function(r,p, titulo) {
  
  csa <-
    corrplot::corrplot(
      r,
      method = "square",
      is.corr = F,
      p.mat = p,
      insig = "label_sig",
      cl.cex = 0.7,
      pch.cex = 0.7,
      win.asp = 1,
      tl.cex = 0.6,
      title = titulo,
      pch.col = "black",
      mar = c(0, 0, 1, 0)
    )
  
  
}

r <- t(as.matrix(modelo2[,-c(14,15)]))
p <- t(as.matrix(p.values))
colors = c("blue", "white", "Red")

ggcorrplot::ggcorrplot(r,p.mat = p,sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7.5,tl.srt = 90,title="Metabolome 53")+scale_fill_gradient2(breaks=c(-4, 4), limit=c(-4,4))
```

### Bivariante

```{r}
obj <- corr.test(tot)
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
obj <- corr.test(tot[obesidad=="Obese",])
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46 Obese")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
obj <- corr.test(tot[obesidad=="No Obese",])
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46 No Obese")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
obj <- corr.test(tot[grupo=="PCOS",])
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46 PCOS")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
obj <- corr.test(tot[grupo=="Female",])
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46 Female")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
obj <- corr.test(tot[grupo=="Male",])
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,type = "upper",sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="Metabolome 46 Male")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

```{r}
# set grid search values for each regularisation parameter
aux.fun <- function(x,y){
  x <- vegdist(t(x),"euclidean")
  y <- vegdist(t(y),"euclidean")
  
  return( c(mantel(x,y)$signif,mantel(x,y)$statistic))

}


X <- tot
ob <- (X[obesidad=="Obese",])
noob <- (X[obesidad=="No Obese",])
female <- as.matrix(X[grupo=="Female",])
male <- as.matrix(X[grupo=="Male",])
pcos <- (X[grupo=="PCOS",])
obfemale <- (X[grupo=="Female" & obesidad=="Obese",])
noobfemale <- (X[grupo=="Female" & obesidad=="No Obese",])
noobmale <- (X[grupo=="Male" & obesidad=="No Obese",])
obmale <- (X[grupo=="Male" & obesidad=="Obese",])
noobpcos <- (X[grupo=="PCOS" & obesidad=="No Obese",])
obpcos <- (X[grupo=="PCOS" & obesidad=="Obese",])


pvals <- c(aux.fun(ob,noob)[1],
aux.fun(female,male)[1],
aux.fun(male,pcos)[1],
aux.fun(female,pcos)[1],
aux.fun(obfemale,noobfemale)[1],
aux.fun(obpcos,noobpcos)[1],
aux.fun(obmale,noobmale)[1],
aux.fun(noobmale,noobpcos)[1],
aux.fun(noobmale,noobfemale)[1],
aux.fun(noobfemale,noobpcos)[1],
aux.fun(obmale,obpcos)[1],
aux.fun(obmale,obfemale)[1],
aux.fun(obfemale,obpcos)[1])

statistics <- c(aux.fun(ob,noob)[2],
aux.fun(female,male)[2],
aux.fun(male,pcos)[2],
aux.fun(female,pcos)[2],
aux.fun(obfemale,noobfemale)[2],
aux.fun(obpcos,noobpcos)[2],
aux.fun(obmale,noobmale)[2],
aux.fun(noobmale,noobpcos)[2],
aux.fun(noobmale,noobfemale)[2],
aux.fun(noobfemale,noobpcos)[2],
aux.fun(obmale,obpcos)[2],
aux.fun(obmale,obfemale)[2],
aux.fun(obfemale,obpcos)[2])

res <- p.adjust(pvals,"BH")

names(res) <- c("Obesidad","sexo","malepcos","femalepcos","obfemale","obpcos","obmale","noobmalepcos","noobsexo","noobfemalepcos","obmalepcos","obsexo","obfemalepcos")

res <- as.data.frame(res)

res$significado <- ifelse(res$res>0.05,"No esta relacionado","Esta relacionado")

res
```

```{r}
sexo <- dat$comunes$variables_in_bacteria$SEX
funcion_pca(X,trans = F,scle = T)
```

## IP

```{r}
dat <- readRDS("../../datos/preprocesado_08_09_23/novoom-04-10-23.rds")

ip <- dat$comunes$ip

ip.d <- as.data.frame(scale(ip))
ip.d$grupo <- grupo
ip.d$obesidad <- obesidad

ip.melt <- reshape2::melt(ip.d)
ggplot(ip.melt,aes(value,color=obesidad))+geom_density()

ip <- as.data.frame(scale(ip))
```

```{r}
mardia(ip)
```

```{r}

mdl2 <- model.matrix( ~ 0 + obesidad * grupo)

colnames(mdl2) <-
  c("NO", "Obesidad", "PCOS", "Male", "PCOSObese", "MaleObese")
contraste <- c(
  pcosfemale = "PCOS-(Obesidad+NO)",
  malefemale = "Male-(Obesidad+NO)",
  pcosmale = "PCOS-Male",
  obesidad = "Obesidad-NO",
  pcosfamaleno = "(PCOS-Obesidad)-NO",
  malefemaleno = "(Male-Obesidad)-NO",
  pcosmaleobeno = "(PCOS-Obesidad)-(Male-Obesidad)",
  pcosfemaleob = "PCOSObese-Obesidad",
  malefemaleob = "MaleObese-Obesidad",
  pcosmaleob = "MaleObese-PCOSObese",
  pcosobese = "PCOSObese",
  MaleObese = "MaleObese",
  FemaleObese = "Obesidad"
)


contrastes <-
  makeContrasts(contrasts = contraste, levels = colnames(mdl2))
fit <- lmFit(t(ip), design = mdl2)
fit2 <- contrasts.fit(fit, contrastes)
fit2 <- eBayes(fit2)

modelo2 <- coef(fit2, Inf)

colnames(modelo2) <- names(contraste)
colnames(modelo2) <- c("PCOS_vs_Female",
                       "Male_vs_Female",
                       "PCOS_vs_Male",
                       "NO_vs_O",
                       "NO_PCOS_Female",
                       "NO_Male_Female",
                       "NO_PCOS_Male",
                       "O_PCOS_Female",
                       "O_Male_Female",
                       "O_PCOS_Male",
                       "PCOS_obese",
                       "Male_Obese",
                       "Female_Obese")

p.values <- sapply(1:13, function(x) topTable(fit2,coef = x,number=Inf)$P.Value)
```

```{r}
r <- t(as.matrix(modelo2[,-c(14,15)]))
p <- t(as.matrix(p.values))
colors = c("blue", "white", "Red")

ggcorrplot::ggcorrplot(r,p.mat = p,sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="IP 46")+scale_fill_gradient2(breaks=c(-2, 2), limit=c(-2,2))
```

# INTEGRACIÓN

```{r,message=F,warning=FALSE}
library(MOFA2)
modelos <- lapply(list.files("./modelos_ip_log/",full.names = T),load_model)
modelo <- MOFA2::select_model(modelos,plot=T)

```

```{r}
p1 <- plot_variance_explained(modelo, max_r2 = 15)

p2 <- plot_variance_explained(modelo, plot_total = T)[[2]]

p3 <- ggarrange(p1, p2)

p3
```

```{r}
plot_factor_cor(modelo)
```

```{r}
factores <- get_factors(modelo)[[1]]
pvalcor <- corr.test(factores)$p
```

RETOMAMOS LAS VARIABLES

```{r}
datos <- readRDS("../../datos/preprocesado_08_09_23/novoom-04-10-23.rds")
grupo <- datos$comunes$grupo
obesidad <- datos$comunes$obesidad
sexo <- datos$comunes$variables_in_bacteria$SEX

x <- datos$comunes$metaboloma[-c(38:40),]
succinato <- colMeans(datos$comunes$metaboloma)
x <- rbind(x,succinato)
rownames(x)[38] <- "Succ"
rownames(x)<- gsub("_mean",replacement = "",x=rownames(x))
x.tmp <- x[-38]
x.tmp <- add_classificacion_metaboloma(x.tmp[-38,])
rownames(x)[-38] <- paste(x.tmp$grupo_meta,rownames(x.tmp),sep="_")
tot <- as.data.frame(transform.in.t(x))
tot <- tot[,order(colnames(tot)),]

grupo <- datos$comunes$grupo
obesidad <- datos$comunes$obesidad

tot$grupo <- grupo
tot$obesidad <- obesidad
tot.melt <- reshape2::melt(tot)

ggplot(tot.melt, aes(value, color = obesidad)) + geom_density()


ip <- dat$comunes$ip

ip.d <- as.data.frame(scale(ip))
ip.d$grupo <- grupo
ip.d$obesidad <- obesidad

ip.melt <- reshape2::melt(ip.d)
ggplot(ip.melt,aes(value,color=obesidad))+geom_density()

ip <- as.data.frame(t(scale(ip)))


metaboloma.t <- t(scale(tot[,-c(39,40)]))
metagenoma <- scale((mean_aldex(datos$comunes$microbiota$genero)))
clinicas <- as.data.frame(modelo@data$clinica[[1]])
clinicas <- (as.data.frame(lapply(clinicas,as.numeric)))
```

```{r}

fac <- 1:ncol(factores)

metaboloma <- modelo@data$metaboloma[[1]]
metagenoma <- modelo@data$metagenoma[[1]]
ip <- modelo@data$ip[[1]]
clinc <- modelo@samples_metadata


pesos <- Reduce(rbind, get_weights(modelo, scale = F))
R <- t(rbind(metaboloma,metagenoma ,ip))
p1 <- funcion_pca(R,scle = F,trans = F)[[1]]
p1
R <- factores[,fac] %*% t(pesos[,fac])
p2 <- funcion_pca(R,scle = F,trans = F)[[1]]
p2
p3 <- funcion_pca(R,scle = F,trans = F)[[1]]
R <- cbind(factores[,fac] %*% t(pesos[,fac]),clinc)
funcion_pca(R,scle =F,trans = F)[[1]]
```

## covariables

```{r}
covariables<- clinc
obj <- corr.test(factores,covariables)
ggcorrplot::ggcorrplot(obj$r ,p.mat = obj$p,sig.level = 0.05,insig = "blank",
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,
                       tl.srt = 90,
                       title="Metabolome 46 Female")+scale_fill_gradient2(breaks=c(-1, 1), limit=c(-1,1))
```

## selección de variables

```{r}

plot_variance_explained_per_feature(modelo,"ip",split_by_factor = T)
plot_variance_explained_per_feature(modelo,"metagenoma",split_by_factor = T)
plot_variance_explained_per_feature(modelo,"metaboloma",split_by_factor = T)
# plot_variance_explained_per_feature(modelo,4)

```

```{r}

```

### seleccion de variables

#### metaboloma

```{r}
umbral <- 0.5
num.fac <- 1:5
feat2.m <- get_weights(modelo,"metaboloma",factors = 1:3,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat.m <- feat2.m
feat2.m <- get_weights(modelo,"metagenoma",factors = 3:5,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat3.g <- feat2.m

feat2.m <- get_weights(modelo,"clinicas",factors = c(1:3),abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.clinicas <- feat2.m

feat2.m <- get_weights(modelo,"ip",factors = c(1:3),abs = T,scale = T)[[1]]

feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.ip <- feat2.m

(feats <- unique(c(feat.m,feat3.g,feats.clinicas,feats.ip)))

R3 <- cbind(factores[,num.fac] %*% t(pesos[feats,num.fac]))
funcion_pca(R3,trans = F,scle = F)[[1]]

clinic <- modelo@samples_metadata[,-c(8,9)]

R3 <- cbind(factores[,num.fac] %*% t(pesos[feats,num.fac]),clinic)
funcion_pca(R3,trans = F,scle = F)[[1]]


```

### comparativa 1

```{r}
//
```

```{r}
umbral <- 0.4
num.fac <- 1:4
feat2.m <- get_weights(modelo,"metaboloma",factors = 1:3,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat.m <- feat2.m
feat2.m <- get_weights(modelo,"metagenoma",factors = 3:5,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat3.g <- feat2.m

feat2.m <- get_weights(modelo,"clinicas",factors = c(1:3),abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.clinicas <- feat2.m

feat2.m <- get_weights(modelo,"ip",factors = c(1:3),abs = T,scale = T)[[1]]

feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.ip <- feat2.m

(feats <- unique(c(feat.m,feat3.g,feats.clinicas,feats.ip)))
pesos <- Reduce(rbind, get_weights(modelo, scale = F))
R3 <- cbind(factores[,num.fac] %*% t(pesos[feats,num.fac]),clinic)


mdl2 <- model.matrix( ~ 0 + obesidad * grupo)

colnames(mdl2) <-
  c("NO", "Obesidad", "PCOS", "Male", "PCOSObese", "MaleObese")
contraste <- c(
  pcosfemale = "PCOS-(Obesidad+NO)",
  malefemale = "Male-(Obesidad+NO)",
  pcosmale = "PCOS-Male",
  obesidad = "Obesidad-NO",
  pcosfamaleno = "(PCOS-Obesidad)-NO",
  malefemaleno = "(Male-Obesidad)-NO",
  pcosmaleobeno = "(PCOS-Obesidad)-(Male-Obesidad)",
  pcosfemaleob = "PCOSObese-Obesidad",
  malefemaleob = "MaleObese-Obesidad",
  pcosmaleob = "MaleObese-PCOSObese",
  pcosobese = "PCOSObese",
  MaleObese = "MaleObese",
  FemaleObese = "Obesidad"
)


contrastes <-
  makeContrasts(contrasts = contraste, levels = colnames(mdl2))
fit <- lmFit(t(R3), design = mdl2)
fit2 <- contrasts.fit(fit, contrastes)
fit2 <- eBayes(fit2)

modelo2 <- coef(fit2, Inf)

colnames(modelo2) <- c("PCOS_vs_Female",
                       "Male_vs_Female",
                       "PCOS_vs_Male",
                       "NO_vs_O",
                       "NO_PCOS_Female",
                       "NO_Male_Female",
                       "NO_PCOS_Male",
                       "O_PCOS_Female",
                       "O_Male_Female",
                       "O_PCOS_Male",
                       "PCOS_obese",
                       "Male_Obese",
                       "Female_Obese")

p.values <- sapply(1:13, function(x) topTable(fit2,coef = x,number=Inf)$P.Value)


r <- t(as.matrix(modelo2[,-c(14,15)]))
p <- t(as.matrix(p.values))
colnames(p) <- colnames(r)
rownames(p) <- rownames(r)
colors = c("blue", "white", "Red")

p1 <- ggcorrplot::ggcorrplot(t(r),
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="IP 46")+scale_fill_gradient2(breaks=c(-4, 4), limit=c(-4,4))
```

### comparativa

```{r}
umbral <- 0.4
num.fac <- 1:4
feat2.m <- get_weights(modelo,"metaboloma",factors = 1:3,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat.m <- feat2.m
feat2.m <- get_weights(modelo,"metagenoma",factors = 3:5,abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]
feat3.g <- feat2.m

feat2.m <- get_weights(modelo,"clinicas",factors = c(1:3),abs = T,scale = T)[[1]]
feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.clinicas <- feat2.m

feat2.m <- get_weights(modelo,"ip",factors = c(1:3),abs = T,scale = T)[[1]]

feat2.m <- rownames(feat2.m)[apply(feat2.m, 1, function(x) (any(x>umbral)))]

feats.ip <- feat2.m

(feats <- unique(c(feat.m,feat3.g,feats.clinicas,feats.ip)))
pesos <- Reduce(rbind, get_weights(modelo, scale = F))

R3 <- rbind(modelo@data$metaboloma[[1]],
            modelo@data$metagenoma[[1]],
            modelo@data$ip[[1]],
            modelo@data$clinicas[[1]])
R3 <- R3[feats,]

mdl2 <- model.matrix( ~ 0 + obesidad * grupo)

colnames(mdl2) <-
  c("NO", "Obesidad", "PCOS", "Male", "PCOSObese", "MaleObese")
contraste <- c(
  pcosfemale = "PCOS-(Obesidad+NO)",
  malefemale = "Male-(Obesidad+NO)",
  pcosmale = "PCOS-Male",
  obesidad = "Obesidad-NO",
  pcosfamaleno = "(PCOS-Obesidad)-NO",
  malefemaleno = "(Male-Obesidad)-NO",
  pcosmaleobeno = "(PCOS-Obesidad)-(Male-Obesidad)",
  pcosfemaleob = "PCOSObese-Obesidad",
  malefemaleob = "MaleObese-Obesidad",
  pcosmaleob = "MaleObese-PCOSObese",
  pcosobese = "PCOSObese",
  MaleObese = "MaleObese",
  FemaleObese = "Obesidad"
)


contrastes <-
  makeContrasts(contrasts = contraste, levels = colnames(mdl2))
fit <- lmFit((R3), design = mdl2)
fit2 <- contrasts.fit(fit, contrastes)
fit2 <- eBayes(fit2)

modelo2 <- coef(fit2, Inf)

colnames(modelo2) <- c("PCOS_vs_Female",
                       "Male_vs_Female",
                       "PCOS_vs_Male",
                       "NO_vs_O",
                       "NO_PCOS_Female",
                       "NO_Male_Female",
                       "NO_PCOS_Male",
                       "O_PCOS_Female",
                       "O_Male_Female",
                       "O_PCOS_Male",
                       "PCOS_obese",
                       "Male_Obese",
                       "Female_Obese")

p.values <- sapply(1:13, function(x) topTable(fit2,coef = x,number=Inf)$P.Value)


r <- t(as.matrix(modelo2[,-c(14,15)]))
p <- t(as.matrix(p.values))
colnames(p) <- colnames(r)
rownames(p) <- rownames(r)
colors = c("blue", "white", "Red")

p2 <- ggcorrplot::ggcorrplot(t(r),
                       outline.color = "black",colors = colors,
                       ggtheme = "theme_minimal",legend.title = "Mean Value",
                       tl.cex = 7,tl.srt = 90,title="IP 46")+scale_fill_gradient2(breaks=c(-4, 4), limit=c(-4,4))
```

```{r}
p1
p2
```
